### ISSUE TITLE
Verify Grill Bladder Afferent Firing Rate Function

### ISSUE THREAD

**Issue by MJC598** [vinayguntu/LUT_Prelim#10]
Afferents are all seemingly scaled and kept below 10. This may or may not be a bug but needs to be verified to rule it out as a scientific notation issue. Equation is sub-function in block override in feedback_loop.py

**Comment by MJC598** [comment]
Verified per: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4860361/

**Comment by MJC598** [comment]
Need to verify all equations in the block function

**Comment by mccdqw** [comment]
Volume function in code different than paper. Multiplying by 20 in code, not in paper.

**Comment by MJC598** [comment]
20 is used as a scalar for rats. Grill used it per cats. 20 is adjustable and not worth worrying about.
