### ISSUE TITLE
Potential discrepency between graphs and data in system

### ISSUE THREAD

**Issue by MJC598** [vinayguntu/LUT_Prelim#12]
As title says, make sure the data in the system matches the graphs and vice versa. (log files vs output graphs)

**Comment by MJC598** [comment]
@chenziao @vinayguntu [Wouldn't this line have a similar issue where it only bothers with the last value in the spike records?](https://github.com/vinayguntu/LUT_Prelim/blob/master/feedback_loop.py#L259) If we're changing the condition [here](https://github.com/vinayguntu/LUT_Prelim/blob/master/feedback_loop.py#L251) per #11 wouldn't we also need to change this one?

**Comment by mccdqw** [comment]
We actually do not need that line. Since the voiding part is commented out, we don't have the need to account for filling for our purposes. We can comment out this if statement.

**Comment by chenziao** [comment]
Some suggestions for potential issues:

1. Remove the scaling factor 3.0 [here](https://github.com/vinayguntu/LUT_Prelim/blob/4_22_feedbackloop/feedback_loop.py#L201).

2. For calculating the volume [here](https://github.com/vinayguntu/LUT_Prelim/blob/4_22_feedbackloop/feedback_loop.py#L265), replace every tvec[0] by "t = sim.h.t-block_length*1000.0". Also replace [#L299](https://github.com/vinayguntu/LUT_Prelim/blob/4_22_feedbackloop/feedback_loop.py#L299).

**Comment by MJC598** [comment]
I've now made these changes and am running to test. If it works I'll issue and tag a pull request.

**Comment by MJC598** [comment]
> I've now made these changes and am running to test. If it works I'll issue and tag a pull request.

So my OS (Ubuntu 20.04) is cancelling the job due to memory constraints. I have 16 GB DDR4 RAM and 8 GB GDDR RAM so this will limit use on individual machines. Might need to test this on a server for memory constraints
